dist: xenial

language: node_js
#notifications:
#  recipients:
#    - i@yanyiwu.com
#  email:
#    on_success: change
#    on_failure: always
stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:

    - &test
      stage: test
      os: linux
      node_js: "iojs-3"
      env:
        - CXX=g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
#    - <<: *test
#      node_js: "4.0.0"
#    - <<: *test
#      node_js: "5.7.0"
#    - <<: *test
#      node_js: "6.0.0"
#    - <<: *test
#      node_js: "6.9.1"
#    - <<: *test
#      node_js: "7.1.0"
#    - <<: *test
#      node_js: "10.0.0"
#    - <<: *test
#      node_js: "12.0.0"
#    - <<: *test
#      node_js: "13"

    ## deploy linux
    - &deploy
      stage: deploy
      os: linux
      node_js: "6"
      env:
        - CXX=g++
      script:
        - ./node_modules/.bin/node-pre-gyp package
      deploy:
        provider: releases
        token: ${GH_TOKEN}
        file_glob: true
        file:
          - build/stage/*/**
        on:
          branch: master
          tags: true
    - <<: *deploy
      node_js: "7"
    - <<: *deploy
      node_js: "8"
    - <<: *deploy
      node_js: "9"
    - <<: *deploy
      node_js: "10"
    - <<: *deploy
      node_js: "11"
    - <<: *deploy
      node_js: "12"
    - <<: *deploy
      node_js: "13"

    ## deploy osx
    - <<: *deploy
      os: osx
      node_js: "6"
    - <<: *deploy
      os: osx
      node_js: "7"
    - <<: *deploy
      os: osx
      node_js: "8"
    - <<: *deploy
      os: osx
      node_js: "9"
    - <<: *deploy
      os: osx
      node_js: "10"
    - <<: *deploy
      os: osx
      node_js: "11"
    - <<: *deploy
      os: osx
      node_js: "12"
    - <<: *deploy
      os: osx
      node_js: "13"

    ## deploy windows
    - <<: *deploy
      os: windows
      node_js: "6"
    - <<: *deploy
      os: windows
      node_js: "7"
    - <<: *deploy
      os: windows
      node_js: "8"
    - <<: *deploy
      os: windows
      node_js: "9"
    - <<: *deploy
      os: windows
      node_js: "10"
    - <<: *deploy
      os: windows
      node_js: "11"
    - <<: *deploy
      os: windows
      node_js: "12"
    - <<: *deploy
      os: windows
      node_js: "13"